version: '3'
services: 
    be-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: be-service
        restart: always
        ports:
            - 8888:8888
